spring.datasource.slave.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://sql.freedb.tech/freedb_creatorally?useSSL=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=freedb_bhavya
spring.datasource.password=V2Bx3@m7JwC#85W
server.port=8081